## PostgreSQL

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
## sudo docker run --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=1234 -d postgres:lateste